CREATE TABLE `audio_file_properties` (
  `id` bigint(23) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The Unique Identifier for this File',
  `disc_id` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '' COMMENT 'The nams of the disc this recording is located on',
  `directory` text CHARACTER SET latin1 NOT NULL COMMENT 'The directory on the disc where the recording resides',
  `file_name` varchar(200) CHARACTER SET latin1 NOT NULL DEFAULT '' COMMENT 'The name of the recording',
  `file_type` text CHARACTER SET latin1 NOT NULL COMMENT 'The file type of the recording',
  `bitrate` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The rate in bits per second that this recording is represented in',
  `audio_sampling_rate` int(10) unsigned NOT NULL COMMENT 'The audio sampling frequency in hz',
  `audio_channels` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'The number of audio channels this recording has',
  `duration` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The length in minutes of this recording',
  `precise_duration` float NOT NULL DEFAULT '0' COMMENT 'The length of this recording in seconds',
  `file_length` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'The size of this file in bytes',
  `zipped` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Is this recording in a zip file',
  `zip_file` varchar(150) CHARACTER SET latin1 NOT NULL DEFAULT '' COMMENT 'The name of the zip file that this recording is located in',
  `audio_file` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Is this an Audio file',
  `encoding_type` text CHARACTER SET latin1 NOT NULL COMMENT 'Information on the Encoding type of this recording',
  `extra_encode_info` text CHARACTER SET latin1 NOT NULL COMMENT 'Any extra encoding information for this recording',
  `variable_bitrate` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Is this a Variable Bit rate recording',
  `series_id` bigint(23) unsigned NOT NULL DEFAULT '0' COMMENT 'The associated series for this recording',
  `episode_id` bigint(23) unsigned NOT NULL DEFAULT '0' COMMENT 'The associated episode for this recording',
  `source_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The source for this recording',
  `description` text CHARACTER SET latin1 NOT NULL COMMENT 'A description of this recording',
  `rating` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'A favorites rating for this recording',
  `heard` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Have I heard this episode',
  `audio_quality` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'A quality rating for this recording',
  `encoding_quality` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'A rating of the sampling and encoding rates for this recording',
  `media_id` int(10) unsigned NOT NULL DEFAULT '0',
  `album` text CHARACTER SET latin1 NOT NULL COMMENT 'The Album this recording came from',
  `artist` text CHARACTER SET latin1 NOT NULL COMMENT 'The Artist that produced this recording',
  `genre` text CHARACTER SET latin1 NOT NULL COMMENT 'The Genre for this recording',
  `title` text CHARACTER SET latin1 NOT NULL COMMENT 'The title of this recording',
  `year` text CHARACTER SET latin1 NOT NULL COMMENT 'The Album year for this recording',
  `track_no` text CHARACTER SET latin1 NOT NULL COMMENT 'The Album track number of this recording',
  `comment` text CHARACTER SET latin1 NOT NULL COMMENT 'Any comment about this recording',
  `indexed` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Have the files for this Series been matched to episodes',
  `series_name` varchar(150) CHARACTER SET latin1 NOT NULL DEFAULT '' COMMENT 'The Name of the series - iff matched',
  `episode_name` varchar(500) CHARACTER SET latin1 NOT NULL DEFAULT '' COMMENT 'The Name of the episode - iff matched',
  `episode_number` int(10) NOT NULL DEFAULT '0' COMMENT 'The episode Number - iff matched',
  `broadcast_date` varchar(45) CHARACTER SET latin1 NOT NULL DEFAULT 'XX/XX/XXXX' COMMENT 'The date the recording was broadcast - iff matched',
  `request_count` bigint(23) NOT NULL DEFAULT '0' COMMENT 'The number of times this has been requested',
  `last_requested` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'The date this was last requested',
  PRIMARY KEY (`id`),
  KEY `Series_Name_INDX` (`series_name`),
  KEY `Episode_name_INDX` (`episode_name`),
  KEY `File_Name_INDX` (`file_name`),
  KEY `Bit_Rate_INDX` (`bitrate`),
  KEY `Broadcast_Date_INDX` (`broadcast_date`),
  KEY `Sampling_Rate_INDX` (`audio_sampling_rate`)
) ENGINE=InnoDB AUTO_INCREMENT=697823 DEFAULT CHARSET=utf8;